### ISSUE TITLE
TypeError: needs a 'context' argument.

### ISSUE THREAD

**Issue by introquest** [tmpvar/jsdom#1061]
```
$ node -i
> require('jsdom').jsdom()
TypeError: needs a 'context' argument.
    at new Window (/tmp/node_modules/jsdom/lib/jsdom/browser/Window.js:39:26)
    at Object.exports.jsdom (/tmp/node_modules/jsdom/lib/jsdom.js:46:16)
    at repl:1:19
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

jsdom version 4.0.2

**Comment by domenic** [comment]
This error occurs when using Node.js™ instead of io.js: https://github.com/tmpvar/jsdom#install

**Comment by jnicklas** [comment]
I ran into this error, and google didn't lead me here directly, so I spent a good hour or two searching for a solution before figuring out what was wrong. This was with code that had previously worked just fine, and that just suddenly started breaking for seemingly no reason.

Please consider at least adding a hard failure and more descriptive error message on Node, so that your users don't have to waste time unnecessarily.

**Comment by domenic** [comment]
Only users who have something like `"jsdom": "*"` in their package.json will encounter this. Users which have properly pinned to a major version will be fine.

Users with `"jsdom": "*"` in their package.json are going to get extremely cryptic error messages all the time, since every major version has different breaking changes (some of which won't show up until way after startup time!).

**Comment by jnicklas** [comment]
Anyone who chooses to upgrade will encounter this, and the fix won't be immediately obvious. I'm only a casual user of this project and do not follow its development closely.

I totally respect your decision to support Io.js only, that is your prerogative, but you must admit that this is at least quite unusual. At least as someone who does not primarily develop on Node/Io as a platform (I only use it as a test harness, really), I was definitely not expecting this kind of thing, so the fact that Node as a platform could possibly no longer be supported didn't even occur to me, and I didn't check for it.

So my thought process would go something like this: 
1) Upgrade jsdom
2) Tests are broken
3) Hmm let me check if some of the APIs have changed?
4) Nope. Seems fine.
5) Hmmm. Google?
6) Can't find this error documented (after all it could randomly change from release to release)
7) Wtf?
8) Start reading jsdom source code.
9) Still looks fine? What the hell is going on here?
10) Two hours of frustration
11) Damnit, I had work to do
12) Randomly looks at README
13) Only supports IO.js. Huh.

**Comment by domenic** [comment]
Good point about people trying to upgrade running in to this. However, I maintain it's really the same as every other major release of jsdom, and deserves the same treatment. Namely, you have to go look at the changelog if you want a straightforward way of figuring out what will break.

For example, in the upgrade from 2.x to 3.0.0, much code that was naively relying on the `window.location.href` being set to a `file://` URL would break in cryptic ways. The only way to really figure out what was broken was either the kind of extensive frustration your thirteen-step process lists, or ... simply look at https://github.com/tmpvar/jsdom/blob/master/Changelog.md#300. Similarly 1.x to 2.0.0, code that was relying on `level: 2` to enforce anything would get really strange errors when new capabilities started showing up and overriding old level2 versions, since `level` was now ignored. Similarly 0.x to 1.0.0, where Node 0.8 was no longer supported.

The changelog is the solution here, not adding some kind of on-startup check to try to deduce if you are using features or an environment that are not supported.

**Comment by inikulin** [comment]
How about throwing exception with the appropriate message if we run in the node environment?
