### ISSUE TITLE
Can jsdom work with htmlparser2

### ISSUE THREAD

**Issue by Vasanth-Indix** [tmpvar/jsdom#1076]
The stats at https://github.com/inikulin/parse5 says htmlparser2 is faster than parse5. Can JSdom be made to work with htmlparser2?

Performance is a major constraint for my usage and would like to get the best of it.

**Comment by domenic** [comment]
Yes, the parser is configurable. htmlparser2 is not very compliant with the actual HTML Standard though, so I would not use it if I were you.

**Comment by domenic** [comment]
I'd first do profiling to see where the most of your program's time is being spent. If most of it is being spent in parse5 then maybe consider another parser.

**Comment by Sebmaster** [comment]
You can provide the parser in the config object with something like `{ parser: require("htmlparser2") }`.

However, generally, most of the time spent in jsdom is due to the sandbox that has to be created, if you don't require script support for the target page, you can disable processing of scripts and get a big performance boost.
