### ISSUE TITLE
is the code isolation for iframes within single jsdom the same as creating multiple jsdom envs?

### ISSUE THREAD

**Issue by alvarorahul** [tmpvar/jsdom#1138]
Hi folks,

I'm trying to use iframes from multiple untrusted sources and wondering if placing multiple iframes in a single page loaded in jsdom offers the same level of isolation as creating multiple jsdom.envs each with a single iframe?

Also, as I understand, even doing multiple jsdoms, you could still break the isolation, is there any precautions we can take to secure this? Or even maybe detect that some code is trying to break these isolation boundaries?

Cheers,
Alvaro

**Comment by domenic** [comment]
jsdom is not very good at isolation, to be honest. Every jsdom instance currently shares the same prototypes (i.e. we don't have a separate Document.prototype, Node.prototype, etc. for every document, but instead they all use the same one). And since it is implemented in io.js, there is necessarily a lot of leakage back to the io.js environment, e.g. if you walk the prototype chain of any "DOM object" you will end up back at Object.prototype and Function.prototype from the surrounding io.js environment. Function.prototype is especially dangerous since `Function.prototype.constructor === Function` is a type of `eval`, allowing arbitrary code execution in the io.js global scope.

The recommended way to handle isolation is, unfortunately, to spin up a separate process and do all your jsdom-ing in there, only passing known-safe messages back to the main code. However you'll have to be careful even then, as your threat model is an attacker with the ability to execute arbitrary code in the global scope.
