### ISSUE TITLE
support node.js again

### ISSUE THREAD

**Issue by japrescott** [tmpvar/jsdom#1145]
I was wondering since io.js and node.js will be merged together under the "open, neutral, Node.js Foundation", at what point will jsdom function on node.js again? What version of uv does node.js need to have, so that jsdom works? Or will it not be before the nodejs1.0 release regarding the history of joyent's speed?

**Comment by domenic** [comment]
I already answered you in the previous thread. Node.js will be supported once a release is made that is based on the io.js code base. That is indeed the plan---now that the trademark is owned by a foundation instead of by Joyent, we can basically rename io.js to node.js, put together a new major release (my guess is Node.js 5.0), and be merged. At that time jsdom will support Node.js, since it is just a new name for the io.js platform jsdom already supports.

**Comment by japrescott** [comment]
thank you for your detailed answer domenic!

**Comment by ccarpita** [comment]
Is there a specific technical reason why node 0.12.x is not supported by jsdom, or is this more of a political issue?  I can understand why it might be the latter, but if it's the former I would really curious to understand the specific limitations and how they might affect other projects.

**Comment by domenic** [comment]
There is indeed a technical reason. Please see the changelog for jsdom 4.0.0.

**Comment by ccarpita** [comment]
I see you were able to drop the Contextify dependency, and I would say that qualifies as a solid technical reason!
