### ISSUE TITLE
How do I access classes like HTMLElement and TextNode?

### ISSUE THREAD

**Issue by callumlocke** [tmpvar/jsdom#1170]
If I want to do something like this in my code...

```js
if (something instanceof HTMLElement) {
  doSomething();
}
```

Is this possible? I had hoped to be able to do something like `jsdom.HTMLElement`, `jsdom.TextNode` etc. but this doesn't seem to work.

**Comment by domenic** [comment]
You need to create a `window`. Once you have a `window`, you can access `window.HTMLElement`.

Alternately, if you run any code inside that `window`, by e.g. creating `<script>` tags and inserting it into the window's `window.document.body`, that will have access to `HTMLElement` as normal.

Closing, since this isn't an issue with jsdom. If you can't quite figure it out still I'd suggest StackOverflow.

**Comment by Sebmaster** [comment]
Yes, but you need to refer to your window object.

Like this:
```js
var doc = jsdom.jsdom();
var win = doc.defaultView;

if (doc.getElementById('myId') instanceof win.HTMLElement) {
  doSomething();
}
```

Damnit, @domenic beat me to it :(
