### ISSUE TITLE
Line numbers/offsets for nodes

### ISSUE THREAD

**Issue by bterlson** [tmpvar/jsdom#1194]
I have need of knowing what line number in the source document a node comes from. This is so I can display useful errors to authors when they have errors in their markup. You could imagine a symbol on the node that gives row/col info.

Since row/col comes with some cost to performance, you could instead have a symbol for offset and let consumers map to row/col themselves, although the total overhead of consumers re-scanning the document for linebreaks is larger than just doing that work at parse-time.

**Comment by inikulin** [comment]
We have a location info in parse5, shouldn't be hard to implement

**Comment by domenic** [comment]
Making a public commitment to work on this on my next jsdom day. I keep forgetting.

**Comment by domenic** [comment]
@inikulin looking in to this, I think this would become much easier if parse5 kept track of `\n`s (or `\r\n`s??) it encountered and included them in `__location`. Otherwise it's going to be a pain to translate index into line number...

**Comment by domenic** [comment]
@bterlson what would you think is appropriate for implicitly-created nodes? Just null locations?

**Comment by domenic** [comment]
Hmm. After much thinking I have a few options here:

- Wait for @inikulin to update parse5 to include line and column numbers
- Slow down parsing by computing line/column numbers at parsing time
- Have a slow-ish `jsdom.nodeLocation(node)` that does the computation when it is called... at the cost of keeping the original HTML in memory, so that we can compute the line/column number.
- Have an ugly and slow-ish `jsdom.nodeLocation(node, originalHTML)` that does the computation when it is called, and relies on the caller to keep the original HTML around
- Have `jsdom.nodeLocation(node)` return just `{ character }` for now, pending a future expansion to `{ character, line, column }` later. In the meantime jsdom users would have to do the computation themselves.

So, questions:
- @inikulin, do you think you'd be able to update parse5 soon with line + column? Maybe we can avoid this whole debate?
- @bterlson, what do you think of the above tradeoffs?

**Comment by bterlson** [comment]
IMO don't slow down parsing by default for something rarely needed.

On one hand I don't think it's unreasonable to provide only character offsets and let users do the mapping if they need line/col, but on the other hand an efficient implementation requires at least a binary search which is annoying. I like the last option, where line and column can be enabled via config.

**Comment by inikulin** [comment]
@domenic I've had idea adding line/col support for parse5 and I think it will be a good addition for the v2.0 However, I'm on vacation right now, far from my laptop and good internet connection. I'll be back in the mid-september. So, please, fill an issue to the parse5, so it will not get lost in the notifications avalanche I've got right now.
