### ISSUE TITLE
iframe document referrer is undefined

### ISSUE THREAD

**Issue by mfrye** [tmpvar/jsdom#1376]
This is kind of an edge case, but I discovered this with the application I am working on. It looks like it's not being applied when the iframe loads.

```
var iframe = document.getElementsByTagName('iframe');
console.log(iframe[0].contentWindow.document.referrer); // undefined

// Then in the iframe scope
console.log(document.referrer) // undefined
```

**Comment by mfrye** [comment]
Note - I also set the referrer configuration in the main HTML and that is working correctly.

**Comment by domenic** [comment]
Ah good catch. I am pretty sure referrer is supposed to be the main document's URL, although of course we'll want a test.

This should be pretty easy to fix by editing the iframe creation (HTMLFrameElement-impl.js) to pass in the correct referrer. If you're up for a PR, that would be lovely, otherwise I'll try to get around to this soon.

**Comment by mfrye** [comment]
I opened #1377. I wasn't sure whether to use parentDoc.URL or url.href there. Thoughts?
