### ISSUE TITLE
Unable to use with AWS Lambda

### ISSUE THREAD

**Issue by martijnvdgrift** [tmpvar/jsdom#1433]
Hi, im unable to use this with AWS Lambda. Lambda runs on node v0.10.36 and i'm using the jsdom version 3.1.2. Help is appreciated.
Error stack:
http://oi63.tinypic.com/v8dgk2.jpg

**Comment by Joris-van-der-Wel** [comment]
I am guessing that you uploaded your project directory, including node_modules to a linux server?

jsdom 3 has a dependency on a module which uses a native module for node (contextify), normally when you install the dependencies using `npm install`, npm will compile it for you. If you upload node_modules, you will have had to run `npm install` on the same environment as the server.

Newer versions of jsdom do not have this native dependency, however those newer versions require node 4+ (which provides the feature we need out of the box, instead of using contextify)

**Comment by martijnvdgrift** [comment]
Lambda runs on an Amazon Linux AMI image. I did a 'npm install' on a OS X installation, running the same node version as Lambda (0.10.36). The Contexify files are inside the node_modules folder and it's runs on my local machine. When I try to run the same code with a Lambda function, it gives the error.
Are you saying that i need to do an npm install on a Amazon Linux image?

**Comment by Joris-van-der-Wel** [comment]
> Are you saying that i need to do an npm install on a Amazon Linux image?
Yes, or something equivalent. You need at least the same architecture (e.g. amd64), and perhaps some of the system libraries must also be the same (I do not know what contextify requires).

**Comment by martijnvdgrift** [comment]
Thanks, doing a NPM install on Ubuntu 64-bit got it working for me!
