### ISSUE TITLE
How to invoke the listeners in jsdom?

### ISSUE THREAD

**Issue by wempoopl** [tmpvar/jsdom#1434]
Hello everybody!

I would like to ask you about addEventListener method in jsdom. I have several methods which put listeners by addEventListener

`
method () {
this.window.addEventListener('scroll', () => {
console.log('scroll');
})
}
`

and everything would be fine but i try to fire this events in the unit test, for example:

    'metod()': (test) =>
        let s = new scroll({ window: this.window })
        s.after()
        s.w.body.scrollTop = 50
        /* ....tests.... */
    },

and nothing works, I don't see any console.log from listeners and so forth. 

Is there any way to fire event correctly?
Cheers

**Comment by Sebmaster** [comment]
Since jsdom doesn't implement layouting, it won't ever scroll.

You can however trigger all events as normal with `dispatchEvent`.

**Comment by johnbeadle** [comment]
@domenic Can I ask a semi-related follow up question to this topic of event listeners please?

I am trying to unit test some code which dynamically adds some `<link>` tags to the document head. I am creating these elements on the fly and attaching 'load' event listeners through element.addEventListener and supplying a callback to run when they are "loaded" into the DOM.

However this callback never fires. Is there a way in JSDOM to trigger/fake the "load" event listener for a DOM element added to my page?

I have tried using sinon.js to "stub" the `addEventListener` method but it says it is already wrapped? I presume by JSDOM?

Sample code below:

```js
var oLink = document.createElement("link");
        oLink.type = "text/css";
        oLink.rel = "stylesheet";
        oLink.href = url;
        oLink.id = id;

var cssLoadedCallback = function() {
         
            var file = this;
            this.removeEventListener('load', cssLoadedCallback);
            _publishEvent("LoadCSSFile/completed", {
                "file": url
            });
            
        };

oLink.addEventListener('load', cssLoadedCallback, false); // IE9+ and other
document.head.appendChild(oLink);
```

Many thanks in advance,

John

**Comment by Sebmaster** [comment]
@johnbeadle If you're using `jsdom.env` you might need to enable resource loading. See the readme.

If you don't need to actually start requests, you can also just use `element.dispatchEvent` to call load handlers.

**Comment by johnbeadle** [comment]
@Sebmaster Thanks for coming back to me so quickly.

I don't believe I using `jsdom.env` -- instead using the following from the readme

```js
var jsdom = require("jsdom").jsdom;
var document = jsdom("hello world");
var window = document.defaultView;
```

My expectation was that when my code being tested executes `document.head.appendChild(oLink);` the `load` event on the `<head>` would automatically be fired (as it does when I test in the browser) and then my callback `cssLoadedCallback` function would fire, but it never gets there.

I have tried to 'stub' the `addEventListener` method and manually trigger the event using `dispatchEvent` as you suggested...


```js
            document.addEventListener = sinon.stub().returns(
                (function(){
                    console.log('!!!!!!!!!!!!!!!!!!!!!! stub addEventListener')
                    var event = document.createEvent('Event');

                    // Define that the event name is 'build'.
                    event.initEvent('load', true, true);
                    document.head.dispatchEvent(event);
                    console.log(event);
                })()
            );
```

But it does not appear to have made any difference to the logs.

I cannot manually trigger dispatchEvent from the test because the code module is sealed and normally runs in a browser which triggers the event and callback function once the `<link>` tag has been added to the head.

Anything obvious I am doing wrong? Or does jsdom not really behave in this way within Node and Mocha?

Thanks again for your time.
John
