### ISSUE TITLE
Travis browser tests are failing builds again (they work locally)

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1592]
Sigh.

https://travis-ci.org/tmpvar/jsdom/jobs/157356574

Not sure what's going on... It looks like the older browser tests are not being executed at all, but I can't tell if that's because the previous ones are erroring or those are.

```
e 48.0.2564 (Linux 0.0.0): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
e 48.0.2564 (Linux 0.0.0): Executed 0 of 0 ERROR (0.154 secs / 0 secs)
```

looks suspicous...

Presumably this is all some Karma and/or Sauce Labs configuration stuff.

**Comment by domenic** [comment]
@Joris-van-der-Wel any chance you could take a look at this?

**Comment by Joris-van-der-Wel** [comment]
Saucelabs only has old chrome versions available (chrome 48) if you use linux, and the "browser" log is empty (using a selenium command). Running our tests on Windows 10 + Chrome 53 finally gave me a useful log line (https://travis-ci.org/tmpvar/jsdom/jobs/164612531#L3123): 
```json
{
  "source":"javascript",
  "message":"http://localhost:9877/base/node_modules/karma-mocha-webworker/karma-mocha-webworker-client/worker.js?6977d54017bcebaae69471165cc69ce728ad28a4 92:33 Uncaught ReferenceError: window is not defined",
  "timestamp":1475495979449,
  "level":"SEVERE"
}
```

So `window` is used somewhere (instead of `self`). I was able to reproduce this locally just now by typing `rm -rf node_modules` first.  Here is the cause: https://github.com/form-data/form-data/blob/master/lib/browser.js#L2 and it looks like they have an issue open about it https://github.com/form-data/form-data/issues/252

**Comment by Joris-van-der-Wel** [comment]
request@2.58.0 BROKEN (https://github.com/request/request/commits/v2.58.0)
request@2.57.0 WORKS
