### ISSUE TITLE
jsdom cannot be minified with uglify

### ISSUE THREAD

**Issue by jeromecovington** [tmpvar/jsdom#1594]
I am working with an app that has `jsdom` as a dependency in the client, and I can run and use the app locally under my development build just fine. However, when I attempt to do a production build (which is very much the same as development, yet with a minification step via `gulp` and `uglify`) I get an error `JS_Parse_Error`. As an experiment, I swapped in `jsdom-no-contextify` and the production build succeeds and all of the functionality for the app appears fine.

---

Has this been encountered before? Do we know why `jsdom-no-contextify` would be minifiable, yet `jsdom` would not?

**Comment by domenic** [comment]
This has not been encountered before. It sounds like an uglify bug; I have heard elsewhere that uglify has problems with modern JavaScript.

Probably the reason that other module works is because it is a fork of jsdom from many years ago and so doesn't use modern JavaScript features.

Closing, since this is not a jsdom issue, but happy to continue discussion in the closed thread.

**Comment by jeromecovington** [comment]
Thanks, @domenic. Just as a heads up, and in the interest of being thorough, I made sure that I pinned to the most recent version of `gulp-uglify@2.0.0` but was still unable to get `jsdom` to pass through minification.
