### ISSUE TITLE
Iterator regression in 9.5

### ISSUE THREAD

**Issue by darobin** [tmpvar/jsdom#1600]
There is a regression in 9.5 compared to 9.4.2 (and before — this is code that has worked for roughly a year). The following used to work:

```js
for (let $section of document.getElementsByTagName('section')) // …
```

Now it fails with the classic `TypeError: document.getElementsByTagName(...)[Symbol.iterator] is not a function`. I believe the change that introduced the problem was:

https://github.com/tmpvar/jsdom/commit/4b80cd674418736fe4cde25414699440ece07d4c

**Comment by domenic** [comment]
As far as I can tell this is a spec-conformance improvement. [HTMLCollection is not iterable](https://dom.spec.whatwg.org/#interface-htmlcollection).

**Comment by darobin** [comment]
I don't dispute that (sad as it is), and there is a simple workaround in calling code, it's just that it's a breaking change.

**Comment by domenic** [comment]
Sure, but we make breaking changes in patch releases all the time as long as they're for spec-compliance reasons. Pretty much every changelog entry contains such fixes.

Anyway, it turns out I was wrong; [there's an implicit iterableness automatically granted to things with indexed properties](https://heycam.github.io/webidl/#es-iterator). Fun. PR welcome to add it to HTMLCollection.

**Comment by i8-pi** [comment]
I'm looking at implementing this, and I have a couple of questions:

1. I was looking at copying the implementation from NodeList, but NodeList simply uses Array.prototype[Symbol.Iterator], which looks a bit unsafe to me. Is it better to implement it myself?

2. I didn't find a suitable test in web-platform-tests, so I'm thinking of adding one in to-upstream [here](https://github.com/w3c/web-platform-tests/tree/master/dom/collections) that will look very much like  [NodeList-iterable.html](https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/NodeList-Iterable.html) with the names changed. Does that sound right?

**Comment by domenic** [comment]
> I was looking at copying the implementation from NodeList, but NodeList simply uses Array.prototype[Symbol.Iterator], which looks a bit unsafe to me. Is it better to implement it myself?

Nah, reusing that is correct. Per [Web IDL](https://heycam.github.io/webidl/#es-iterator), "If the interface defines an indexed property getter, then the Function object is %ArrayProto_values%."

> I didn't find a suitable test in web-platform-tests, so I'm thinking of adding one in to-upstream here that will look very much like NodeList-iterable.html with the names changed. Does that sound right?

Yeah, except that HTMLCollection is not "iterable" per Web IDL, it just "has an iterator" (since it defines an indexed property getter). So per spec it should not have forEach, entries, values, and keys. Testing for the *absence* of those would be good, actually, so just flipping the assertion around.

**Comment by i8-pi** [comment]
I see, thanks! I'll have a PR ready shortly
