### ISSUE TITLE
Deleting a custom window property does not work

### ISSUE THREAD

**Issue by venyii** [tmpvar/jsdom#1622]
Hi,

the #jsdom IRC channel told me to open an issue about this:

I'm unable to (completely) delete a window property that I added myself. The value will remain the same.

**Failing test case:**

``` js
specify("Create, modify and delete custom window property", () => {
  const window = jsdom.jsdom().defaultView;

  assert.equal(window.XXX, undefined);
  assert.equal('XXX' in window, false);

  window.XXX = 1;
  assert.equal(window.XXX, 1);

  window.XXX = 2;
  assert.equal(window.XXX, 2);

  delete window.XXX;
  assert.equal(window.XXX, undefined); // Fails here
  assert.equal('XXX' in window, false);
});
```

**Test Result:**

```
  1) jsdom/miscellaneous Create, modify and delete custom window property:
     AssertionError: expected 2 to equal undefined
```

**Working in Chrome DevTools:**

![screen shot 2016-10-04 at 15 28 49](https://cloud.githubusercontent.com/assets/502368/19075993/5d97aace-8a47-11e6-875e-5a5684b283b4.png)

Tested with `9.5.0` and `master#7b11f2b`

**Comment by i8-pi** [comment]
See https://github.com/nodejs/node/issues/6287

Someone please correct me if I'm wrong. To my understanding, this problem happens when `ProcessExternalResources` in `config.features` is set to `['script']` (https://github.com/tmpvar/jsdom#external-resources). This effectively runs
```js
window = vm.runInContext("this", window)
```
which populates the window object with the global object properties (such as `eval`, `Math` etc) *outside* of the vm (these are automatically defined inside the vm), but exposes the linked nodejs bug as a side effect.

If you can live without `eval`, `Math` etc defined on the window object outside of the sandbox, you can do
```js
const window = jsdom.jsdom('', { features: { ProcessExternalResources: false }}).defaultView;
```

**Comment by domenic** [comment]
Fixed in Node.js, so we should be good to go.

**Comment by venyii** [comment]
@domenic do you have a reference/link for me? Thanks!

**Comment by domenic** [comment]
Look back a few comments.

**Comment by AmareshB** [comment]
delete command return false, when we try to delete a property on window or global object. Then how did ti work for `delete window.XXX` in the first command?
