### ISSUE TITLE
Regression in parsing big DOM structures

### ISSUE THREAD

**Issue by vsemozhetbyt** [tmpvar/jsdom#1625]
On revisiting [the old issue](https://github.com/tmpvar/jsdom/issues/1490), I've found the last jsdom (9.6.0) does not handle big DOM structures as well as previuos versions. Please, try this modified code from that issue (I've tested in Node 7 beta):

```js
/******************************************************************************/
'use strict';
/******************************************************************************/
const fs = require('fs');
const jsdom = require('jsdom');
/******************************************************************************/
const html =  fs.openSync('test.html', 'w');

fs.writeSync(html,
  '\uFEFF<!doctype html><html><head><meta charset="UTF-8"><title></title></head><body>\n\n',
null, 'utf8');

const elementsNumber = 1000;
let   counter = elementsNumber;

while (counter--) {
  fs.writeSync(html, `<a href='${counter}.html'>${counter}</a>\n`, null, 'utf8');
}

fs.writeSync(html, '\n</body></html>\n', null, 'utf8');
/******************************************************************************/
const hrStart = process.hrtime();

jsdom.env({
  file: 'test.html',
  done: () => {
    const hrEnd = process.hrtime(hrStart);
    console.log(`Parsed ${elementsNumber}: ${(hrEnd[0] * 1e9 + hrEnd[1]) / 1e9} s\n`);
  },
});
/******************************************************************************/
```

Some results with different `elementsNumber`:

```
Parsed   1000:  0.7295047  s
Parsed  10000: 88.95351464 s
Parsed 100000: well, I had been waiting more than 30 minutes and then I have aborted it.
```

**Comment by domenic** [comment]
Do you have an idea of the last version that was able to handle these quickly?

**Comment by vsemozhetbyt** [comment]
jsdom 9.5.0
```
Parsed 10000: 93.806245369 s
```
jsdom@9.4.5
```
Parsed  10000: 0.99649875 s — almost 100 times faster
Parsed 100000: 7.039270563 s — in the 9.6.0 I had been waited 30 min till abortion
```

**Comment by domenic** [comment]
Fascinating! I guess it's probably related to the HTMLCollection changes, but it's hard to understand why, as HTMLCollection *should* be irrelevant during parsing, and in general created lazily. Anyway, this is very helpful, and should be enough to let me debug next time I get a jsdom hack day. Further investigation is of course appreciated, but this will get me started.

**Comment by vsemozhetbyt** [comment]
I can't get any further with `perf`, it gives strange data, see key fragments:
jsdom 9.4.5
```
 [Summary]:
   ticks  total  nonlib   name
     29   18.4%   18.4%  JavaScript
      0    0.0%    0.0%  C++
     17   10.8%   10.8%  GC
      0    0.0%          Shared libraries
    129   81.6%          Unaccounted

 [Bottom up (heavy) profile]:
   ticks parent  name
    129   81.6%  UNKNOWN
     80   62.0%    C:\Program Files\nodejs\node.exe
      9    5.7%  Handler: _localName
      1   11.1%    C:\Program Files\nodejs\node.exe
      6    3.8%  Stub: RecordWriteStub
```
jsdom 9.6.0
```
 [Summary]:
   ticks  total  nonlib   name
   1562    6.2%    6.2%  JavaScript
      0    0.0%    0.0%  C++
    253    1.0%    1.0%  GC
      0    0.0%          Shared libraries
  23654   93.8%          Unaccounted

 [Bottom up (heavy) profile]:
   ticks parent  name
  23654   93.8%  UNKNOWN
   1408    6.0%    C:\Program Files\nodejs\node.exe
   1218    4.8%  Stub: RecordWriteStub {8}
```
So I can't catch the bottleneck function in a simple user way. Sorry.

**Comment by Joris-van-der-Wel** [comment]
Have you tried running the benchmark in chrome? In my experience that profiler is much better than node's.  See also https://github.com/tmpvar/jsdom/issues/1560#issuecomment-231989129

**Comment by vsemozhetbyt** [comment]
Thank you. It seems there are enough unknown steps in this way for me to make more mess than help.

**Comment by domenic** [comment]
Tracked it down. The issue was introduced by this change: https://github.com/tmpvar/jsdom/commit/a7cd5a160fd6c295fa80e953fdf051a1c5dc5cf5#diff-ca21879157deb80d8c691cea34961451L232

That is, before, inserting an element would simply update the version of the parent. Now, it walks the parent and child graph and updates their versions as well, which is expensive since the tree walking is expensive.

This was a necessary change to properly invalidate certain caches. But I think that at the very least it's not necessary during initial parsing. So right now I'm leaning toward disabling it during that time, although it's possible there might be better solutions (e.g. avoiding the tree walk by using recursion or similar).

**Comment by domenic** [comment]
In particular, as you might expect from the symbol-tree documentation, it's the treeIterator (i.e. inclusive descendants iterator) that is expensive; the ancestors iterator is not a contributor.

**Comment by domenic** [comment]
Further info:

Prior to https://github.com/tmpvar/jsdom/commit/4be8634f4121286454f6f559551ca06b0b967b68, pretty much every HTMLCollection was rooted at the document. Thus, when things changed, it sufficed to increment the document version; that would correctly tell the HTMLCollection that it needs an update.

But in https://github.com/tmpvar/jsdom/commit/4be8634f4121286454f6f559551ca06b0b967b68, I said "that's silly; why would a HTMLCollection for `select.options` be rooted at the document? It should clearly be rooted at the `select`." So I switched that. That broke some stuff, since we weren't properly versioning non-document nodes. So in https://github.com/tmpvar/jsdom/commit/a7cd5a160fd6c295fa80e953fdf051a1c5dc5cf5 I fixed that by doing the ancestor/descendant iteration and incrementing those versions. But, as described above, that makes things slow.

I'm still not sure what the best fix is, but now I see at least a few options:

- Introduce a "batch mode" for changes, used mostly for parsing (maybe also innerHTML/outerHTML/textContent?). It delays all version-incrementing to one single pass at the end.
- Go back to the previous setup and root all HTMLCollections at the document. Add a giant warning to _version explaining that it isn't as useful as you think it is. Maybe even remove _version from non-document nodes entirely.
- Try just not incrementing the descendant versions. When I comment out the descendant-version-incrementing code, all tests still pass! Not so for the ancestor-version-incrementing code. So maybe only incrementing the ancestor version is important!? I need to think harder to see if that could possibly be true... but it seems plausible.
