### ISSUE TITLE
Can we have a standard method to do this common use-case of jsdom?

### ISSUE THREAD

**Issue by dmitrymakhnin** [tmpvar/jsdom#1638]
The use case is

```
getPage({
    'url': 'http://www.this-page-intentionally-left-blank.org/',
    'cookie': 'likesCookies=true',
    'onload': function(err, window) {}
});
```

**Comment by domenic** [comment]
I don't have a plan to do that. In particular customizing cookies is not that common, and waiting for onload instead of e.g. parsing to finish is not common either. You can easily create such a method yourself, although that will be easier when [newapi](https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md) finally lands.
