### ISSUE TITLE
pathname empty for urls without http

### ISSUE THREAD

**Issue by AvraamMavridis** [tmpvar/jsdom#1704]
Right behavior

```js
var a = document.createElement('a')
a.href = '/table/configurator/'
console.log(a.pathname) 
// '/table/configurator/'
```

What happens in jsdom

```js
var a = document.createElement('a')
a.href = '/table/configurator/'
console.log(a.pathname) 
// ''
```

**Comment by domenic** [comment]
This is probably because you are using the default jsdom URL of `about:blank`. If you navigate to `about:blank` in your browser and run that code you'll find the same thing.

Closing since I am 99% sure that is the case, but will certainly reopen if I'm wrong. If so please provide a full repro file I can run with `node test.js`.
