### ISSUE TITLE
location could work just like it does in the browser

### ISSUE THREAD

**Issue by capaj** [tmpvar/jsdom#1717]
Utilizing getters and setters, location object on a window could be implemented to work just like in the real browser. Is this something worth implementing? Would you be open to merging such PR @domenic ? I'd love to take a stab at it, if it is something you'd consider for desirable.

**Comment by domenic** [comment]
What do you mean, exactly? How does location not act like a browser? We don't implement navigation, because doing so involves creating an entirely new Window/Document/every other class. Are you proposing to work on a PR for that? Please link to the spec section that you were thinking of implementing.

**Comment by capaj** [comment]
navigation is what I meant. I wasn't sure if it wasn't out of scope for jsdom. Good to know that it is out of scope. No need to waste time on that inside jsdom's repo.

**Comment by capaj** [comment]
@domenic If you don't mind me asking-why don't you implement navigation? It should not be impossible to make JSdom's `window` behave like a real browser when navigating.

**Comment by domenic** [comment]
Because it's very hard.
