### ISSUE TITLE
TypeError: Cannot read property '_location' of null on ubuntu 16.10

### ISSUE THREAD

**Issue by capaj** [tmpvar/jsdom#1783]
Here's the important bit of my output:
```
 RUNS  src/components/Analyse/Widget/Criteria/DateRange.test.js
/home/capaj/git_projects/be/frontend-be.com/node_modules/jsdom/lib/jsdom/browser/Window.js:148
      return idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._location);
                                                                              ^

TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (/home/capaj/git_projects/be/frontend-be.com/node_modules/jsdom/lib/jsdom/browser/Window.js:148:79)
    at Timeout.callback [as _onTimeout] (/home/capaj/git_projects/be/frontend-be.com/node_modules/jsdom/lib/jsdom/browser/Window.js:525:40)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

```

This happens with jest 19.0.2, node 7.7.2 and jsdom "9.11.0".
My colleagues with Macbooks don't get this error. I get it randomly in any testcases which happen to run at that time.

**Comment by capaj** [comment]
I tried the most primitive way of patching that exception and it worked:
https://github.com/tmpvar/jsdom/compare/master...capaj:patch-1?expand=1

With that I don't get any exceptions and my whole suit of tests runs fine until the end.

**Comment by domenic** [comment]
Please post a repro that does not involve third party libraries like jest, and that I can run. Error messages are not sufficient to debug your problem. Will reopen if such a repro is provided.

**Comment by cdaringe** [comment]
@capaj, did you find a solution?

**Comment by capaj** [comment]
Not really. I tried running jest in multiple workers and that helped. It would still popup once a while but it did not fail the tests. I don't think I'll be able to reproduce it on a smaller scale.

**Comment by rahimrahman** [comment]
@capaj, I'm on a Macbook and I get this quite often.  Sometimes it crashes my test, sometimes it doesn't.

@domenic what do I need to post to help?  What's a repro?

**Comment by domenic** [comment]
If you open a new issue you'll see an issue template you can fill out; please pay attention to the requirements there.

**Comment by rickyk586** [comment]
@domenic I believe this is a race condition with window.close() deleting `this._document` and stopping the timers. It would probably fix it to ensure the timers are all stopped before deleting it.

I notice that `get location()` is being called from a timer AFTER `calling window.close()`

**Comment by khrome83** [comment]
I am seeing this issue is well. I can't share my code, because I have no clue what is triggering this. It shows when I run my `jest` tests.

The funny thing is that on my MacBook Pro, I don't see it. But in my CI enviroment which is Linux based I do.

I never saw it before today.

**Comment by sholanozie** [comment]
In case anyone else is running into this issue, this is what worked for me in Fedora 25:

`yarn add jest jest-cli`
`yarn global add jest jest-cli`

After running these commands, I stopped seeing this error.

**Comment by ryanhomer** [comment]
I haven't quite figured out exactly why I got this error message but I'll note my situation here in case it helps someone. In my case I have two separate Jest tests in one test file. Each of the tests uses a redux store backed by a mock LocalStorage that's stored in `global.localStorage` via JSDOM. I am rendering with enzyme's `mount`.

When I use Jest's `beforeAll` function to set up my `store` var and attempt to use this store for both tests, I get the '_location' error. However, when I use `beforeEach` instead which sets up a new store for the second test (still using the same common `store` var), then the tests go through without the error.

I do not see why reusing the existing store should cause an issue but it seems like something is getting cleaned up inadvertently before the second test starts.

**Comment by brandonaaskov** [comment]
This is currently the only open issue tracking this problem: looks like the other ones were closed down due to lack of a way to reproduce it. I too am hitting this, and it's not related to Ubuntu as far as I can tell.

However, @domenic asked for an example that doesn't use a library like Jest. Jest is probably the reason _most_ people are seeing this. But the issue is coming from a file from the jsdom library. If anything, I think you _should_ be using Jest to reproduce the issue.

**Comment by Zirro** [comment]
@brandonaaskov Jest is currently using an old version of jsdom (9.12.0), but they will upgrade to version 11.x in their next major release. Until we know whether the issue remains in recent versions, there's not much to do here.

**Comment by brandonaaskov** [comment]
@Zirro Jest actually [_just_ updated to use jsdom@11](https://github.com/facebook/jest/commit/cfbda8017ad80d08ccc69de40a6eeddc11545f8f), but even after upgrading jest I'm still seeing the same issue.

@domenic said he was investigating in issue #1893, but then later just closed the ticket with no feedback.

**Comment by domenic** [comment]
I remain uninterested in spending my spare time debugging Jest. If people provide any evidence that this problem is caused by jsdom, I'm excited to fix it, but until then, I have to assume it's a problem with Jest, and plan to spend no more time on it.

**Comment by brandonaaskov** [comment]
@domenic I understand you don't have interest in debugging Jest, but it _is_ kind of the elephant in the room. It's a massively popular library that uses jsdom by default, so I was kind of hoping you'd be more excited to fix it. It doesn't give me the warm and fuzzies that you're so quick to dismiss the issue, no matter how many people bring it up.

**Comment by Zirro** [comment]
@brandonaaskov While I see can where you're coming from, it is no easier for us to debug this through Jest than it is for you. We're all doing this in our spare time, with this large project being available to you at no cost.

I don't suppose you could help investigate this instead? That would give me the warm-and-fuzzies.

**Comment by brandonaaskov** [comment]
@Zirro I've been plugging away at it trying to track it down. I actually don't think it's a jsdom issue either, but I still haven't figured out the root cause. I'm building up from the most basic example I can think of to try and reproduce the problem. My current thinking is that it's actually related to one of the redux packages we're using, but we'll see. I'll report back with my findings :)

**Comment by Zirro** [comment]
@brandonaaskov That's encouraging to hear. Good luck!

**Comment by brandonaaskov** [comment]
@Zirro and @domenic, I haven't been able to isolate it to the line yet, but I'm 95% sure the culprit is the `redux-persist` package (at least in my case), which makes sense given its reliance on `window`. If I completely remove that package from my project, the problem goes away.

I _haven't_ been able to replicate this issue with a standalone project with some basic tests (_not_ including `redux-persist` yet). This just further shows that `jsdom` is _not_ the culprit.

I'm about to check out for the weekend but wanted to mention that in case it helps future travelers. I'll keep digging on this over the next week.
