### ISSUE TITLE
Event handlers set from outside don't run unless you set { runScripts: "dangerously" }

### ISSUE THREAD

**Issue by kitsonk** [tmpvar/jsdom#1828]
### Basic info:

- **Node.js version:** 6.9.1
- **jsdom version:** 10.0.0

### Minimal reproduction case

```js
const jsdom = require('jsdom');

const dom = new jsdom.JSDOM(`
<!DOCTYPE html>
<html>
<head></head>
<body></body>
</html>
`);

const document = dom.window.document;

const div = document.createElement('div');
document.body.appendChild(div);
div.onclick = function () {
	console.log('I was clicked.');
}

const event = document.createEvent('CustomEvent');
event.initEvent('click', true, true);
div.dispatchEvent(event);
```

You get no output, though it is expected that `onlick` property would have been called.

### How does similar code behave in browsers?

[Logs `I was clicked.` as expected](https://jsfiddle.net/kitsonk/nr0g1ksz/)

Also, similar code worked in jsdom v9.

**Comment by vsemozhetbyt** [comment]
It seems you need to add `, { runScripts: "dangerously" }` according to https://github.com/tmpvar/jsdom#executing-scripts

**Comment by kitsonk** [comment]
That does resolve the issue, though I would say that is totally non-obvious in that there were no obvious scripts.  Setting element listeners via setting the property directly on the element is a super common way and lots of developers wouldn't realise that issue when writing isomorphic code.

**Comment by kitsonk** [comment]
Also, the documentation does say "inline event handlers", but I would expect still that most developers would not consider setting a property from the _outside_ to be an inline event handler.  Even `"outside-only"` doesn't allow the handler to execute.

**Comment by Sebmaster** [comment]
jsdom.jsdom previously set `runScripts: "dangerously"` implicitly. This has now been made explicit.

**Comment by kitsonk** [comment]
@vsemozhetbyt yes, I realise that, but I am dealing with testing some code written in the above way, which previously worked when running against jsdom v9.  I converted over to the new API, only to find that tests that ran previously stopped working.

@Sebmaster yes, I understand that.  My main point now is that the documentation does not make it obvious that the pattern above is actually considered an inline event handler.  It was counter intuitive.  The only examples in the documentation refer to inline script tags.  Even if there was an examples that had something like `<div onclick="console.log('I was clicked.'></div>` I don't think many developers would have assumed that that was the same thing as `document.createElement('div'); div.onlick = function () { console.log('I was clicked.'); }` and considered an _unsafe_ inline script.

**Comment by domenic** [comment]
This does seem like a bug, although I'm not sure how fixable it will be to detect onclick set from outside vs. inside.

**Comment by domenic** [comment]
I thought a bit about how to implement this. We have the following cases:

1. Event handler properties set from the outside (the OP's issue)
2. Event handler properties set from the inside
3. Event handler attributes set during parsing
4. Event handler attributes set from the outside using `setAttribute` (and friends).
5. Event handler attributes set from the inside using `setAttribute` (and friends).

jsdom cannot distinguish between (1) + (2) and between (4) + (5). However, (2) and (5) are only really relevant in `runScripts: "dangerously"`, since you can't run code inside otherwise.

(1) should work even with `runScripts: undefined`, I think.

(3) should be restricted to `runScripts: "dangerously"` because of the classic danger case where you point your `JSDOM.fromURL()` at an untrusted URL, and it includes script in its `onload=""` attribute that formats your hard disk.

My big question is about (4). I'm not sure where it lands. I can see arguments for allowing it with `runScripts: undefined`, or only with `"outside-only"`, or only with `"dangerously"`. What do others think?

**Comment by kitsonk** [comment]
I think (4) is more closely related to (3), in the sense that _usually_ only works when the attribute existed on the original document during parsing, and are _just_ as dangerous.  It might be arguable that they are equal to `"outside-only"` but essentially there is a risk that unsanitised strings could be being added to an attribute.

It is clearly different than the other two forms which you would expect to just work:

```js
const div = document.createElement('div');
div.onclick = (e) => console.log(e); /* known scope */
div.addEventListener('click', (e) => console.log(e)); /* known scope */

div.setAttribute('onclick', '(e) => console.log(e)'); /* eval is evil */
```

**Comment by Austral1a** [comment]
> FWIW, this works without `{ runScripts: 'dangerously' }`:
> 
> ```js
> const jsdom = require('jsdom');
> 
> const dom = new jsdom.JSDOM(`
>   <!DOCTYPE html>
>   <html>
>   <head></head>
>   <body></body>
>   </html>
> `);
> 
> const document = dom.window.document;
> 
> const div = document.createElement('div');
> document.body.appendChild(div);
> 
> div.addEventListener('click', function () {
>   console.log('I was clicked.');
> });
> 
> const event = document.createEvent('CustomEvent');
> event.initEvent('click', true, true);
> div.dispatchEvent(event);
> ```

This is an old-fashioned way, for old browsers. And `initEvent` method is deprecated now.
