### ISSUE TITLE
Cannot working with react-router-dom

### ISSUE THREAD

**Issue by zaaack** [tmpvar/jsdom#1831]
### Basic info:

- node: v6.3.1
- jsdom: ^10.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
  const wrapper = mount(<Root />)
  wrapper.find('a.topics-link').simulate('click') // a.topics-link is `<Link to="/topics" className="topics-link">Topics</Link>`
//  wrapper.find('a.topics-link').simulate('click', {button: 0})
 // nothing change
```
JSDOM's click event doesn't have {button: 0}, and cause `Link` component won't working 

See: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L41

Relevant: https://github.com/tmpvar/jsdom/issues/1559

**Comment by domenic** [comment]
As noted in the issue template, we can't help debug issues that use non-JavaScript syntax like JSX or undefined functions like mount(). We'll happily reopen if you can provide an actual minimal example.

**Comment by zaaack** [comment]
@domenic Sorry for my late, it's an old issue so I didn't create a demo, here is an online demo just created, hope would help.

**Comment by domenic** [comment]
Hmm, maybe I wasn't clear. The problem isn't that you're lacking a demo. The problem is that you expect us to debug things that (a) involve third-party libraries, which we can't be responsible for debugging the interaction with; (b) involve syntax such as JSX that does not run in our environment.

Basically you're asking us to debug your program, instead of debugging a problem with jsdom, and we're not support staff. Such issues are better asked of your coworkers.

If you can create a minimal repro that does not use third-party libraries (like react, react-dom, react-router-dom) and uses only standard JavaScript syntax, we can help. But until then it's not something we can help with.

**Comment by zaaack** [comment]
@domenic I get it. The demo is updated, https://runkit.com/zaaack/demos, please check out.

**Comment by domenic** [comment]
Great, thanks; that is perfect! Now that we've established what the actual issue is, and that it's not caused by JSX or react-router, we can see that this is the same issue as #1559. I will roll it into that by renaming #1559 to be a bit more general.
