### ISSUE TITLE
HTMLFrameElement's Javascript URL are incorrectly resolved and executed

### ISSUE THREAD

**Issue by tsirolnik** [tmpvar/jsdom#1836]
### Basic info:

- **Node.js version:6.10.0** 
- **jsdom version:10.1.0**

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM(`
  <html>
<body>
    <iframe  src='javascript:window.location.replace("https://whatsoever.com/?a=b&c=5&x=y")'></iframe>
</body>
</html>
`);

```

This causes an error of `Unexpected token`

The fix is simple and straightforward. In "HTMLFrameElement-impl.js" line 75 in the method loadFrame the code needs to change from this - 
```js
contentWindow.eval(url.pathname);
```
to something like this - 
```js
// Slice and join the array, in case of having the "javascript:" in the script itself.
// e.g - javascript:alert('This script was executed via the javascript: scheme');
let scriptArr = srcAttribute.split('javascript:').slice(1);
let scriptToEval = scriptArr.join('javascript:');
contentWindow.eval(scriptToEval);
```

### How does similar code behave in browsers?

Pasting `javascript:window.location.replace("https://whatsoever.com/?a=b&c=5&x=y")` in the browser's window will result in a redirection happening

**Comment by domenic** [comment]
I think the bug here is in the URL parser, actually. You propose a workaround, but we shouldn't need that; we should fix the URL parser.

**Comment by domenic** [comment]
Well, I guess at least per the HTML spec, they do something similar: https://html.spec.whatwg.org/#navigate steps 12.2-12.3

**Comment by domenic** [comment]
The latest in https://github.com/whatwg/url/issues/307 indicates this is a bug in our handling. We need to implement the navigate algorithm better, where it:

- Serializes the URL (into a string)
- Removes the leading "javascript:"
- Percent decodes the result (into bytes)
- UTF-8 decodes that (back into a string)

This is a little tricky, but is possible to pull request if you're up for it. Otherwise I can try to work on this sometime when I have free time.

**Comment by tsirolnik** [comment]
I'm not sure that I understood the concept of your proposed solution but I'll give it a try and see how it goes
