### ISSUE TITLE
jsdom bug when a BOM is a present in an HTML file

### ISSUE THREAD

**Issue by dontcallmedom** [tmpvar/jsdom#1898]
### Basic info:

- **Node.js version:** 6.10.3
- **jsdom version:** 11.0.0

### Minimal reproduction case

```js
const {JSDOM} = require("jsdom");
const fs = require("fs");

const file = fs.readFileSync(process.argv[2]).toString("utf8");
const dom = new JSDOM(file)
console.log(dom.window.document.querySelector("head title").textContent);
```
When calling this script on a simple html file such as
```html
<!DOCTYPE html>
<html>
  <head>
    <title>
      Test BOM
    </title>
  </head>
  </html>
```
this fails when the said starts with a BOM, works when the BOM is removed. It looks like for some reason, the BOM causes jsdom to close the create an empty `<head>`, and push the actual content of the head to the body.

### How does similar code behave in browsers?

Browsers correctly parse the DOM in this situation.

**Comment by inikulin** [comment]
Yeah, actually jsdom need to strip BOM on it's side. Previously BOM handling was in the HTML spec, but lately it was removed from preprocessor and parser expects input stream to be a UTF-16 string.

**Comment by domenic** [comment]
This is an interesting one.

If you had fed me the bytes directly, i.e. omitted the `.toString("utf8")`, then I would have put them through the decoder (which is the preprocessor step @inikulin alludes to). That would have stripped the BOM.

However, you gave me a string. That string explicitly had a BOM in it, because you made sure of that, by using Node's `utf8` decoder, which [does not strip the BOM](https://github.com/nodejs/node-v0.x-archive/issues/1918). jsdom's decoder is [more sophisticated](https://encoding.spec.whatwg.org/#utf-8-decode), but Node's is not.

We don't really have a spec for what happens if you feed me a string instead of bytes; that's now how browsers work. But I think it's best to just take the string as given. If we strip BOMs, why not strip whitespace too? Replace lone surrogates with a replacement character? Etc.

So in my opinion this is working as intended. Curious what others think.

**Comment by dontcallmedom** [comment]
that makes sense to me; I think it would be useful to document it explicitly though.
