### ISSUE TITLE
get width of actual image

### ISSUE THREAD

**Issue by fghhfg** [tmpvar/jsdom#1980]
Can jsdom get width and height of actual image? I want to parse my offline website and write something back.

this is my code:
```js
var file_path = process.argv[2];
var fs = require('fs');
var content = fs.readFileSync(file_path, 'utf8');

const jsdom = require("jsdom");
const { JSDOM } = jsdom;
let dom = new JSDOM(content);

console.log(content);

let imgs = dom.window.document.getElementsByTagName('img');
for (var i = 0; i < imgs.length; i++) {
    //dom.window.document.getElementsByTagName('img')[i].width = dom.window.document.getElementsByTagName('img')[i].naturalWidth;
    console.log( imgs[i].width ); // only return 0 either width or naturalWidth or clientWidth
}

//fs.writeFileSync('index.2.html', content);
```

ref:
https://stackoverflow.com/questions/19914111/get-dom-elements-actual-width-using-jsdom

**Comment by Zirro** [comment]
Yes, have a look at the [Loading subresources](https://github.com/tmpvar/jsdom#loading-subresources) section of the README.

**Comment by fghhfg** [comment]
still return 0...

since it's a offline website, I just use `image-size` anyway

```js
var file_path = process.argv[2];
var fs = require('fs');
var content = fs.readFileSync(file_path, 'utf8');

const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const options = {resources: 'usable'};
let dom = new JSDOM(content, options);

let imgs = dom.window.document.getElementsByTagName('img');
console.log( imgs[1].clientWidth ); // still return 0
```

---
1. `npm install canvas-prebuilt`
2.  pass the `resources: "usable"` option
```js
const options = {resources: 'usable'};
let dom = new JSDOM(content, options);
```
ref: https://github.com/tmpvar/jsdom/issues/1843

**Comment by Sebmaster** [comment]
You can't use `clientWidth`. Only `width` and `height` are supported for canvas/image.

**Comment by 0x5e5e** [comment]
@fghhfg why did you close this issue?   This hasn't been resolved, you just used a workaround specific to your use case.

@Sebmaster `width` and `height` don't work either in this scenario.   since the image is loaded async via [resourceLoader](https://github.com/tmpvar/jsdom/blob/37532c74235c9eb0260bdcf424719c8e3d7b129b/lib/jsdom/living/nodes/HTMLImageElement-impl.js#L12-L23) getting the width will return 0 because the resource hasn't been retrieved yet.

@fghhfg this solution worked for me:
`                let imgs = dom.window.document.getElementsByTagName('img');
                console.log( imgs[1].clientWidth ); // still return 0

                dom.window.document.onload = function(d) {
                    console.log(img[1].width); // returns correct width 
                }`
