### ISSUE TITLE
dom nested-ness altered !! 

### ISSUE THREAD

**Issue by Belloliva** [tmpvar/jsdom#2049]
### Basic info:

- **Node.js version: v8.9.1 ** 
- **jsdom version: 11.3.0** 

### Minimal reproduction case

```js
const jsdom = require("jsdom"); 
const { JSDOM } = jsdom;

const dom = new JSDOM(`
<p> 
OuterToFigureBefore
<figure>
InnerToFigure
</figure> 
OuterToFigureAfter
</p>
`); 
console.log(dom.window.document.querySelector("body").outerHTML);
```

### What I get in terminal 
```
$ node index.js
<body><p> 
OuterToFigureBefore
</p><figure>
InnerToFigure
</figure> 
OuterToFigureAfter
<p></p>
</body>
```

Sorry if this is the ultimate beginner question, I started using the jsdom module yesterday :)

**Comment by Zirro** [comment]
This is correct according to the spec, and browsers behave in this way as well. HTML parsers contain many interesting behaviours in order to remain compatible with all the existing markup out there.

You can see the DOM structure generated by your browser on this page: http://software.hixie.ch/utilities/js/live-dom-viewer/

**Comment by domenic** [comment]
Note that you ignored the section of the issue template about "how does this code behave in a browser".

**Comment by Belloliva** [comment]
indeed, chrome does the same !!
