### ISSUE TITLE
Switch to vime module for VM contexts

### ISSUE THREAD

**Issue by TimothyGu** [tmpvar/jsdom#2095]
Currently, we use Node.js core's [`vm` module](https://nodejs.org/api/vm.html) for context isolation. The way `vm` module works regarding the global object is unfortunately pretty fragile and [bug-prone](https://github.com/nodejs/node/issues?q=is%3Aissue+label%3Avm), while also providing [subpar performance](https://github.com/nodejs/benchmarking/issues/75#issuecomment-262740252) when accessing global properties due to its design. Node.js' release cycle also prevents some `vm` bug fixes from reaching older release lines, thus decreasing our options regarding the versions of Node.js to support.

The [`vime` module](https://github.com/bnoordhuis/vime) provides a refreshing alternative. It is very bare bones, as it doesn't provide access to the global object (only the global `this` value / proxy) nor does it specify interceptors (in C++) on the global object. But that isn't really a problem for us as we can mostly `Object.setPrototypeOf(this, Window.prototype)` our way out of it. And for other advanced features of `WindowProxy` such as indexed properties access a la `frames[0]` and cross-origin access, I am reasonably confident we can do a good enough job emulating the former, while the latter seems way too bug-prone to implement even with the flexibility `vm` currently offers.

But it's not all sunshine and rainbows. `vime` module is a native module, which may incur barriers on jsdom's adoption (since we are currently all JS, which may change when the WebSocket API gets merged as `ws` *can* use a more performant C++ layer), nor can it be very easily portable to the ABI-stable N-API. Being very simplistic at the moment, it doesn't provide the flexibility the existing `vm` module does with regards to `vm.Script`. (Adding support for it in `vime` is easy, but being compatible with existing `vm` module's `Script` objects is near impossible due to APIs being private and ABI not frozen.) It does not have the options the `vm` module provides on running `Script`s like timeouts, <kbd><kbd>Ctrl</kbd>+<kbd>C</kbd></kbd>, and pretty errors, though we don't expose those at the moment either. It's also unclear whether it would be possible for `vime` to integrate with Node.js Inspector (currently, it is not).

The solid core `vime` presents is still very desirable for heavy `vm` users like jsdom though, and I do believe the pros outweigh the cons when implementing new features such as the named properties object (#1129; which exposes [somewhat-bugs](https://chromium-review.googlesource.com/c/v8/v8/+/816515) in V8!) and separate classes for Windows (#1453). I could also talk to bnoordhuis about possibly having an equivalent of `vime` in Node.js' core, which would solve most of the issues I described above. Being so simple, it can be a palatable addition to Node.js even for small-core advocates, and I believe it would be a good candidate for backporting to older Node.js branches as well.

With the understanding that @domenic was the author of the current iteration of the `vm` module in Node.js, I am very interested in hearing what he thinks. But general opinions are more than welcome.

**Comment by domenic** [comment]
I don't think this is a good idea. Native dependencies impose such a huge cost on consumers. I'm even a bit worried about the `ws` module now that you mention it, despite it only using optional native dependencies.

In particular, I think bumping our minimum Node version would be less disruptive than requiring native modules.

I think instead we should work to evolve the core vm module as much as possible ourselves. If the performance is subpar by design, we should work on introducing a new mode to it that fixes these shortcomings. I'm not sure what that would look like; I'd like to see a more fully fleshed out design for implementing WindowProxy's exotic features, and Window's non-exotic ones, before proposing it. vime doesn't seem like quite enough to me, but I'm willing to be convinced. (My thought would be something along the lines of creating a realm with no global proxy built in, but you can specify what the global `this` value is. Then we create our own `Proxy` for `WindowProxy` and have that be the global this.)
