### ISSUE TITLE
Support post on fromURL?

### ISSUE THREAD

**Issue by bluelovers** [tmpvar/jsdom#2117]
### Basic info:

- **Node.js version:** 
- **jsdom version:** 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  method: 'POST',
			form: {
				keyword: '',
				compType: '',
				Page: i+1,
			},
};

JSDOM.fromURL(`a url that need use post`, options).then(dom => {
  console.log(dom.serialize());
});

... your code that reproduces the problem here, probably using dom.window ...
```

### How does similar code behave in browsers?

(Link to a jsbin or similar suggested.)

**Comment by domenic** [comment]
See https://github.com/tmpvar/jsdom#fromurl

> The initial request is not infinitely customizable to the same extent as is possible in a package like request; fromURL() is meant to be a convenience API for the majority of cases. If you need greater control over the initial request, you should perform it yourself, and then use the JSDOM constructor manually.

**Comment by robinmetral** [comment]
I'm also interested in this, since I'm having to work with pages that will only render when `POST`ed to (😭).

If we use something like `node-fetch` under the hood, are there blockers to exposing options for that library (`method` etc) as part of the `fromURL` options? Seems like it wouldn't be breaking, and fairly straightforward to implement—but I might be missing something? 

The motivation for this is that I don't like having to install and use a request library separately for this, when one is already packed into `jsdom` 😅 hopes this makes sense!

**Comment by domenic** [comment]
We specifically want to keep fromURL() small, so we have no plans to expand it.

**Comment by robinmetral** [comment]
How would forwarding options to the request library under `jsdom` make `fromURL` bigger? Anyways I don't mind much, I'm using the constructor already like I mentioned—just thought that this would be a low-hanging fruit for an improved DX 🤷 

Thanks anyways for the answer

**Comment by bluelovers** [comment]
> I'm also interested in this, since I'm having to work with pages that will only render when `POST`ed to (😭).
> 
> If we use something like `node-fetch` under the hood, are there blockers to exposing options for that library (`method` etc) as part of the `fromURL` options? Seems like it wouldn't be breaking, and fairly straightforward to implement—but I might be missing something?
> 
> The motivation for this is that I don't like having to install and use a request library separately for this, when one is already packed into `jsdom` 😅 hopes this makes sense!

try this https://www.npmjs.com/package/jsdom-extra
