### ISSUE TITLE
Explain how we are different from PhantomJS/Selenium

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#959]
This is the number-one question asked by people when I gave my talk about jsdom. We should include something in the readme (or at least wiki, linked to by the readme).

**Comment by jcrben** [comment]
Have you came up with anything in response? I noticed you have a January 2015 slide at  http://www.slideshare.net/domenicdenicola/the-jsdom but it doesn't seem to mention this question.

**Comment by domenic** [comment]
Lots of thoughts, but they're all stuck in my head; just haven't had the time to write them down.

**Comment by jcrben** [comment]
OK. I moved on to phantomjs to scrape a dynamic website. I'm not sure if I had to, but it seemed to be the most straightforward for my need.

**Comment by dreaddy** [comment]
bump ?? @jcrben @domenic

**Comment by dominhhai** [comment]
How jsdom differ from PhantomJS?

**Comment by Joris-van-der-Wel** [comment]
> How jsdom differ from PhantomJS?

Phantomjs is a complete browser (although it uses a very old and rare rendering engine). It even performs rendering (for example you could take a screenshot). You need to run an executable to run phantomjs; it has to be compiled for all the different platforms.

jsdom is not a full browser, it does not perform rendering, nor does it support navigation (clicking on links). It _does_ support DOM, HTML and canvas, running scripts in a sandbox. 

So you could use jsdom to fetch the html of your web application (while also executing the javascript code within that html). And then you are able to examine/modify the resulting DOM tree.  Or you could trigger event listeners to test how the web application reacts.

Or you could use jsdom to build up your own DOM tree and then serialize to a html string.

Jsdom runs wherever node.js runs. you could even run jsdom within a different browser (afaik this is the only way to create a DOM Document within a web worker).

One of the reasons jsdom is used a lot for testing is that creating a new document instance has very little overhead. Opening a new browser or opening tabs using selenium costs a lot of time, so running a lot of small tests in fresh documents could take minutes in selenium, but only seconds using jsdom.

Another import benefit jsdom has for testing is a bit more complicated: If you are testing a javascript heavy web application, you can very easily suffer from race conditions if you use phantomjs or selenium. For example if you create a script to test something using selenium, that script will live in a different process than the website. If you perform multiple steps that are dependent on one another (for example: `step 1. find element`; `step 2. click on that element`), the application might change the DOM during those steps (`step 1. find element`; `element removed by javascript`; `step 2 click on that element` -> `StaleElementReferenceException`). This is not an issue in jsdom because your tests live in exactly the same thread and event loop as the web application, if your test is executing then javascript code of the web application can not run until your test releases control to the event loop

React uses jsdom to test their stuff (https://github.com/facebook/react).

**Comment by dominhhai** [comment]
💯 👍 
 awesome answer!!!
Thank you very much! 
Thought that it should be noted on Readme or Wiki page.

**Comment by kapouer** [comment]
Not to complain, but there's also https://github.com/kapouer/node-webkitgtk which is not as old, is based on webkit (the one that comes from safari), and is powering several linux web browsers like epiphany, midori. It's designed to be easy to use, to be compilable from a system-installed library (think rpm, deb), and i'm actually using it to prerender web pages, output pdf or png. It also sports a very useful cli. Just saying...

**Comment by domenic** [comment]
I don't think it's Jason's responsibility to advertise every browser-ish project.

**Comment by bagermen** [comment]
I do not understand how jsdom could be used for tests while it works in different way then a browser..
OK.. Let's say I have button. I need to test that if I click it then I see a popup. 
I do not use React. I use pure JS.. 
or another example. If I need to test something that uses Promises but you wrote that jsdoc works in 1 Thread it means that this case can't be tested with jsdoc.. So why does someone use jsdoc at all???

**Comment by bagermen** [comment]
I suppose that there is no value in test that test nothing.. I mean if jsdoc is not a browser then it can't test browser behavior it just pretend to be a browser.. hm..

**Comment by kim366** [comment]
I am torn between testing stuff in JSDOM and Selenium. Selenium is so slow that you can't really use it for TDD but JSDOM is a synthetic environment that cannot test whether IE does the correct thing. So TDD with JSDOM and then write the same thing in Selenium such that I can run it on LambdaTest?..

**Comment by Joris-van-der-Wel** [comment]
> I am torn between testing stuff in JSDOM and Selenium. Selenium is so slow that you can't really use it for TDD but JSDOM is a synthetic environment that cannot test whether IE does the correct thing. So TDD with JSDOM and then write the same thing in Selenium such that I can run it on LambdaTest?..

All of this depends on your use case. If you want to click through a web application with "real" browsers, then WebDriver (selenium) is one of the few things that works cross browser. 

If you want to run unit/integration tests with javascript code and DOM, then you have a lot more choices. JSDOM is great because it is so simple to set up, you only need node.js and NPM. When using a real browser there are a lot more things to worry about, such as: 

* How are you installing the browsers, from a package manager (e.g. apt-get)? What if you want to test using different versions of the same browser?
* How limited are the hardware resources of your CI environment? For example if you use the free version of travis, you will often encounter timeouts when testing with a real browser.
* Do you have to cleanup zombie browser processes? Some CI environments will solve this problem for you because they start with a fresh VM or container. If you are using jenkins you have to solve this yourself.
* How can you make it easy for other devs in your team to run the tests locally?

If you still want to use a browser for unit/integration tests, there are many choices. Karma is nice because it works in every browser, without requiring WebDriver, all the browser has to do is visit a special URL. 

Of course WebDriver also works (e.g. using the "wd" package). If you inject your whole test suite at once it will not be slow to execute. There is also a protocol command which lets you execute asynchronous code in a browser using a callback (`/session/:sessionId/execute_async`). 

There are also some solutions that are more specific to a certain browser, such as using the debugging protocol or something with WebExtension.

**Comment by bitsapien** [comment]
@kim366 You could actually use https://testing-library.com/ . This uses JSDOM underneath, and adds things like event triggering to it, along with most of the "nice-ities" you get with Selenium. This has been my favorite tool and you can surely use it with TDD.
